### ISSUE TITLE
Smoodge Delay Feedback not zero

### ISSUE THREAD

**Issue by ThaYoost** [wgd-modular/loewenzahnhonig-firmware#12]
Hey,

Can't fully wrap my head around why, but the Smoodge Delay feedback parameter stays on even though the pot is totally to the left. If I simply ping it with the feedback pot closed it still  gives me 3 pings back. I added a simple check at line 171 which seems to solve it.
  

```c++
    if ( delayFeedback <= 0.02f){
      delayFeedback = 0.0f;
    }
```

**Comment by fxwiegand** [comment]
I think @gamecat69 can probably help with that one as he wrote the mentioned delay himself.

**Comment by gamecat69** [comment]
Hi @ThaYoost thanks for raising the issue.

However, I am unable to recreate it. When I set my feedback knob to the lowest setting I get just one echo.
@fxwiegand are you able to recreate this issue by any chance?

Based on the fix that you implemented, I suspect either a dodgy pot that does not close all the way, or some analogue noise perhaps caused by a power supply or some other form of interference.

One other thought.... Note that unless you are using the alt firmware, feedback is controlled using the sum of the feedback pot and CV2. If you are you may have CV going to CV2 or any analogue noise on both the pot and CV2 is making a small problem slightly larger.

Kind Regards,
Nik

**Comment by ThaYoost** [comment]
Right. That option slipped my mind. Indeed just a faulty pot. Thanks for the quick response guys.
Rene

**Comment by fxwiegand** [comment]
@ThaYoost Great to hear the issue is solved! Indeed faulty pots are a real pain - especially in digital modules!

@gamecat69 Thanks for taking care of this 🙏🏻

**Comment by ThaYoost** [comment]
Had a similar issue with the divisor by the way. The pot3value is not consistently on 0.0f so the if statement doesn't consistently evaluate true. Easily fixed when I gave it a tiny bit of space, like <= 0.02
